ALTER TABLE `accounts_transaction` ADD INDEX( `account_id`);
ALTER TABLE `accounts_transaction` ADD INDEX( `account_type`);
ALTER TABLE `accounts_transaction` ADD INDEX( `item_type`);
ALTER TABLE `accounts_transaction` ADD INDEX( `record_date`);
ALTER TABLE `accounts_transaction` ADD INDEX( `payment_medium`);
ALTER TABLE `accounts_transaction` ADD INDEX( `academic_year`);
ALTER TABLE `accounts_transaction` ADD INDEX( `academic_term`);
ALTER TABLE `accounts_transaction` ADD INDEX( `date_created`);
ALTER TABLE `accounts_transaction` ADD INDEX( `reversed`);
ALTER TABLE `accounts_transaction` ADD INDEX( `state`);
ALTER TABLE `accounts_transaction` ADD INDEX( `status`);
ALTER TABLE `fees_collection` ADD INDEX(`recorded_date`);
ALTER TABLE `fees_collection` ADD INDEX(`has_reversal`);
ALTER TABLE `events` ADD INDEX(`end_date`);
ALTER TABLE `events` ADD INDEX(`event_type`);
ALTER TABLE `events` ADD INDEX(`state`);
ALTER TABLE `events` ADD INDEX(`item_id`);
ALTER TABLE `events` ADD INDEX(`client_id`);
ALTER TABLE `events` ADD INDEX(`start_date`);
ALTER TABLE `events` ADD INDEX(`status`);
ALTER TABLE `events` CHANGE `state` `state` ENUM('Pending','Cancelled','Held','Ongoing','Over') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'Pending'; 
